Add PR template
Otus-DevOps-2021-08/lburinov73_infra pull request #1
Opened 2021-09-16 04:14 UTC by lburinov73

homework: added PR template

2021-09-16 07:59 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Оставил коментарий к файлу. ДЗ возвращаю на доработку =)

2021-09-16 07:59 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Вот сюда смотрим внимательно, нужно что бы тесты проходили =)

2021-09-16 14:48 UTC, lburinov73 commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Исправил. :)

2021-09-17 10:34 UTC, mrgreyves approved these changes
Здравствуйте!) Вот теперь апрув!)

2021-09-20 04:58 UTC, merged